import React, { useState } from 'react';

export type ProfileMemory = { id: string; scope: 'user' | 'project' | 'sensitive'; key: string; value?: string; hasValue?: boolean; updatedAt: string };

export function FridayProfilePanel({ memories, onSave, onDelete }: { memories: ProfileMemory[]; onSave: (memory: { scope: 'user' | 'project'; key: string; value: string }) => Promise<void>; onDelete: (id: string) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [key, setKey] = useState(''); const [value, setValue] = useState(''); const [scope, setScope] = useState<'user' | 'project'>('user'); const [saving, setSaving] = useState(false);
  const save = async () => { if (!key.trim() || !value.trim()) return; setSaving(true); try { await onSave({ scope, key, value }); setKey(''); setValue(''); } finally { setSaving(false); } };
  return <section className="mx-auto mb-5 w-[calc(100%-2rem)] max-w-6xl rounded-2xl border border-stone-200 bg-white px-4 py-3 shadow-sm">
    <div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold tracking-wide text-stone-500">FRIDAY CONTEXT</p><p className="text-xs text-stone-600">Save only what you want FRIDAY to remember across sessions.</p></div><button type="button" onClick={() => setOpen(!open)} className="rounded-xl border border-stone-300 px-3 py-2 text-xs font-semibold text-stone-700 hover:bg-stone-50">{open ? 'Done' : 'Manage memory'}</button></div>
    {open && <div className="mt-4 border-t border-stone-100 pt-4"><div className="grid gap-2 sm:grid-cols-[120px_1fr_1fr_auto]"><select value={scope} onChange={(e) => setScope(e.target.value as 'user' | 'project')} className="rounded-xl border border-stone-300 px-3 py-2 text-xs"><option value="user">About me</option><option value="project">Project context</option></select><input value={key} onChange={(e) => setKey(e.target.value)} placeholder="e.g. preferred_name" className="rounded-xl border border-stone-300 px-3 py-2 text-xs" /><input value={value} onChange={(e) => setValue(e.target.value)} placeholder="e.g. Alex" className="rounded-xl border border-stone-300 px-3 py-2 text-xs" /><button type="button" disabled={saving} onClick={save} className="rounded-xl bg-orange-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Save</button></div><p className="mt-2 text-[11px] text-stone-500">Saving is explicit. Sensitive values are not collected here and are never sent to a model prompt.</p><div className="mt-3 space-y-1">{memories.length ? memories.map((memory) => <div key={memory.id} className="flex items-center justify-between rounded-lg bg-stone-50 px-3 py-2 text-xs"><span><b>{memory.scope}</b> · {memory.key}: {memory.scope === 'sensitive' ? '[protected]' : memory.value}</span><button type="button" onClick={() => onDelete(memory.id)} className="text-rose-600">Forget</button></div>) : <p className="text-xs text-stone-500">Nothing saved yet — totally fine.</p>}</div></div>}
  </section>;
}
